### ISSUE TITLE
compilation error with GCC 6 and 7

### ISSUE THREAD

**Issue by grunjol** [MoneroOcean/node-cryptoforknote-util#1]
This happens with most of the forks of node-cryptonote-util, and lot of people already sent PR on those forks, its a simple C struct name declaration

Issue https://github.com/zone117x/node-cryptonote-pool/issues/175
PR (on Snipa22 branch): https://github.com/Snipa22/node-cryptonote-util/pull/2 
that solves the issue.

I'v been using that patch in my production servers with GCC 6 and 7 without any problem.

**Comment by MoneroOcean** [comment]
Thanks for letting me know. Fix was applied: https://github.com/MoneroOcean/node-cryptoforknote-util/commit/26c6ff80758f3b6c8aeb191f13527676af46c079

**Comment by grunjol** [comment]
That was fast!
I can compile xmr-node-proxy now without any custom modification on AESNI (and non-) on GCC 5, 6 and 7.

Thanks
