### ISSUE TITLE
Dose it cant by used for BCN?failed to parse block.

### ISSUE THREAD

**Issue by Tupeipei** [MoneroOcean/node-cryptoforknote-util#3]
When I used it for mining bytecoin, it returned the err "failed to parse block".

**Comment by MoneroOcean** [comment]
Maybe you need to use blob_type equal to 2.

**Comment by netmebtc** [comment]
I have meet the same issue, and sure the  blob_type  is 2

**Comment by muscleman** [comment]
I'm getting this error too.
seems this line is the issue
return utils.cnUtil.convert_blob(this.buffer, cnBlobType).toString('hex');
